# Generated by Django 2.2.12 on 2020-10-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='lokasi',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
